# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.5.3.dev75+gc773752.d20221121'
__version_tuple__ = version_tuple = (0, 5, 3, 'dev75', 'gc773752.d20221121')
